version: "3.5"
services:
  api:
    build: .
    container_name: api
    depends_on:
      - mysql
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app

    networks:
      - nestjs-docker
  mysql:
    build: .
    container_name: mysql
    image: mysql:5.7
    volumes:
      - ./src/database/data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_PORT: 3306
      MYSQL_DATABASE: miichisoft-docker
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - nestjs-docker
networks:
  nestjs-docker:
