version: '3.5'
services:
  backend:
    container_name: container-api
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    ports:
      - 8000:3000
    volumes:
      - ./:/usr/src/app
    networks:
      - nestjs-docker

  mysql:
    image: mysql:5.7.22
    container_name: container-mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: database_mysql
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./src/database:/var/lib/mysql
    networks:
      - nestjs-docker
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      MYSQL_ROOT_PASSWORD: miichisoft
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root

    networks:
      - nestjs-docker
    volumes:
      - /sessions

networks:
  nestjs-docker:
